services:
  - type: web
    name: mrphone-backend
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: node-cache
      mountPath: /opt/render/project/src/node_modules
      sizeGB: 1
